[package]
description = " Netfilter NFLOG high-level bindings"
license = "GPL-2.0+"
keywords = ["netfilter","log","nflog"]
homepage = "https://github.com/chifflier/nflog-rs"
repository = "https://github.com/chifflier/nflog-rs.git"

name = "nflog"
version = "0.9.0"
authors = [ "Pierre Chifflier <chifflier@wzdftpd.net>" ]

[dependencies]
libc = "0.2.0"
log = "0.4"
